name: flutter_app
description: Template project for flutter apps.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+10000000 #1 00 00 000


environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: 3.32.0


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1

  # Navigation
  auto_route: 10.1.0+1

  # Data Structures
  freezed_annotation: 3.1.0
  json_annotation: 4.9.0

  # Network
  dio: 5.8.0+1

  # Storage
  shared_preferences: 2.5.3

  # Firebase
  firebase_analytics: 12.0.0
  firebase_auth: 6.0.0
  firebase_core: 4.0.0
  firebase_crashlytics: 5.0.0
  firebase_messaging: 16.0.0
  firebase_remote_config: 6.0.0

  # Authentication
  google_sign_in: 6.3.0
  sign_in_with_apple: 7.0.1

  # Device
  device_info_plus: 11.5.0
  package_info_plus: 8.3.0
  path_provider: 2.1.5
  window_manager: 0.5.1

  # Security
  freerasp: 7.2.1

  # Logging
  pretty_dio_logger: 1.4.0
  talker: 4.4.7
  talker_flutter: 4.4.7
  talker_dio_logger: 4.4.7

  # Resources
  extended_image: 10.0.1
  flutter_native_splash: 2.4.6
  flutter_svg: 2.2.0
  intl: 0.20.2

  # UI
  flutter_animate: 4.5.2
  flutter_local_notifications: 19.4.0
  modal_bottom_sheet: 3.0.0
  universal_html: 2.2.4

  # Utility
  app_settings: 6.1.1
  collection: 1.19.1
  crypto: 3.0.6
  permission_handler: 12.0.1
  url_launcher: 6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Build Runner
  build_runner: 2.4.15

  # State management
  riverpod_generator: 2.6.5

  # Navigation
  auto_route_generator: 10.0.1

  # Data Structures
  freezed: 3.0.6
  json_serializable: 6.9.5

  # Resources
  flutter_gen_runner: 5.11.0

  # Lint
  custom_lint: 0.7.5
  flutter_lints: 6.0.0
  netglade_analysis: 18.0.0
  riverpod_lint: 2.6.5

  # UI Tests
  patrol: 3.18.0


patrol:
  app_name: flutter_app
  android:
    package_name: cz.helu.flutter.template
  ios:
    bundle_id: cz.helu.flutter.template


flutter_gen:
  output: lib/assets/

  integrations:
    flutter_svg: true


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/png/
    - assets/svg/

  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay.ttf
